version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    env_file: ./backend/docker/.env.mariadb
    volumes:
      - alliance-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - alliance_network

networks:
  alliance_network:
    driver: bridge
volumes:
  alliance-db-data:
