volumes:
  alliance-db-data:

services:
  nginx:
    container_name: alliance_nginx
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
      - ../backend/api/upload:/var/www/sites/alliance/upload
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
    env_file:
      - .env

  mysql:
    container_name: alliance_mysql
    image: mysql:8.0
    env_file:
      - .env
    volumes:
      - alliance-db-data:/var/lib/mysql
    ports:
      - 3306:3306